### ISSUE TITLE
feature : Firebase Setting

### ISSUE THREAD

**Issue by moonkey48** [BostonGosari/Outline#1]
## ✏️ Summary
작성된 ERD를 바탕으로 Firebase의 FireStore 세팅

<br>

## ✨ Description

Realtime Database와 Cloud FireStore중 FireStore가 다양한 쿼리와 정렬등의 기능 제공 및 최근에 나온 서비스라는 점에서 FireStore로 구현을 결정하였습니다. 기존 러너중 FireStore를 쓰신 분이 계셔서 참고 리소스를 요청드릴 예정입니다. 추가로 구현할 ERD 링크를 첨부합니다. 
[ERD: Outline](https://app.diagrams.net/#G1nJsQc0XEeYouTOukrcmJ3J8uaFMR7a2m)

<br>

기능명세 내용
1 | Firebase 설정 | 유저 데이터 저장 | Firebase Setting | 구조도를 바탕으로 Firebase FireStore 세팅
-- | -- | -- | -- | --

<br>

## ✓ Todo
- [x] FireBase SPM 설정
- [x] FireStore EnvironmentObject 설정
- [ ] 기본 FireStore 연결 모델 구현

<br>

**Comment by hyunjuntyler** [comment]
🎉🥳드디어 개발이 시작되었군요!! 벌써 기획도 많이 하고 개발단계라니 감회가 새롭네요

다같이 ERD 확인해보고 MapKit 이나 HealthKit 쪽에서 사용하는 변수명을 최대한 사용하는 방법도 좋을 것 같다고 생각하는데 어떻게 생각하시나요? 저도 ERD 최대한 빠르게 확인하면서 변수명 같이 고민해보겠습니다!!

**Comment by moonkey48** [comment]
@hyunjuntyler 너무 좋은 의견입니다! 오늘내일중으로 FireStore 및 Model 구현 예정이라 오늘까지 ERD에서 추가 및 수정되어야 하는 부분 코멘트 혹은 직접 수정해주시면 반영하도록 하겠습니다:)

@yoohyebin @chamroro 참고해주시면 감사하겠습니다! 

[ERD: Outline](https://drive.google.com/file/d/1nJsQc0XEeYouTOukrcmJ3J8uaFMR7a2m/view?usp=sharing)

**Comment by chamroro** [comment]
@moonkey48 ERD 내용이 깨져서 글씨가 안보입니다 ㅠㅠ 혹시 PDF로 뽑아서 공유해주실 수 있을까요?

**Comment by hyunjuntyler** [comment]
> @moonkey48 ERD 내용이 깨져서 글씨가 안보입니다 ㅠㅠ 혹시 PDF로 뽑아서 공유해주실 수 있을까요?

https://app.diagrams.net/#G1nJsQc0XEeYouTOukrcmJ3J8uaFMR7a2m 이곳으로 들어가도 안보이시나요? 한번 더 클릭하면 편집할수있는 것이 뜹니다!

**Comment by yoohyebin** [comment]
확인해봤는데 mapKit관련된 부분 저는 오스틴이 작성해준 변수명대로 사용해도 될거 같습니다!!

**Comment by chamroro** [comment]
운동 기록 관련된 부분을 확인했습니다! 저는 체크하는 입장인데도 머리가 뽀개질것같은데 일단 넘 고생하셨어요 ㅠㅠ 
변수 보단 구조에 대해서 여러가지 고민이 많이 드는데, 파이어베이스 프로젝트 하나 파서 그걸 보면서 이야기하는게 서로에게 이해가 더 빠를 것 같기도 합니다 ! 아무래도 ERD만 보고는 저 테이블간이 컬렉션인지, 문서인지, 문서안의 컬렉션인지 이해가 안가서요 ,, ㅠㅠ 

일단 제가 이해한바로 코멘트를 드리자면,
1. Record 안에서 courceName과 courceLength은 GPS 러닝의 경우 선택한 코스에 대한 정보인가요? 만약 그렇다면, GPSArtCource 컬렉션에 있는 id만 넣고 참조하는건 어떤가요 ..? runningType에 따라 저장하는 데이터가 다르다른데, 현재는 record안에 map과 운동 데이터들이 섞여 있으니 수정이 필요할 것 같습니다!

2. running 관련 데이터는 모두 string으로 바꿔주실 수 있나요? 이미 제 코드에 포메터가 있습니다! 해당 데이터들은 firestore에서 꺼내서 수정할일이 없을 것 같아 string으로 저장해도 좋을 것 같습니다. Workout Extension 아래 첨부합니다! 변수명은 제걸 바꾸겠습니다 ㅎㅎ 

<img width="466" alt="스크린샷 2023-10-14 오후 11 11 40" src="https://github.com/BostonGosari/Outline/assets/76644652/1727047d-57f6-404e-a5fc-6d22eca61e25">

많은 대화가 필요한 부분을 맡으셨네요 ㅎㅎ 엄청 좋은 경험이 될 것 같아요!  오스틴 화이팅 !!! 💪🏻
