### ISSUE TITLE
data : 데이터 분기 처리

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#103]
## ✏️ Summary
- iOS 데이터 분기 처리 최적화

<br>

## ✨ Description
- 자유러닝 시작시 이전에 시작된 GPS Art 로 시작되는 것 처리
- 초기화 구문 관리
- 모든 러닝이 자유러닝으로 되는 오류 처리

<br>

## ✓ Todo
- [x] 자유러닝 시작시 이전에 시작된 GPS Art 로 시작되는 것 처리
- [ ] 초기화 구문 관리
- [x] 모든 러닝이 자유러닝으로 되는 오류 처리
