### ISSUE TITLE
feat : 미니 가이드 경로 구현

### ISSUE THREAD

**Issue by yoohyebin** [BostonGosari/Outline#105]
## ✏️ Summary
- GPS 러닝 뷰에 들어갈 미니 가이드 경로 구현

<br>

## ✨ Description
- GPS Art 러닝을 할 때 제공되는 미니 가이드 경로를 구현합니다.
- 전체 코스를 표시하고 그 위에 현재 위치를 그립니다.
- 맵을 클릭하면 크기가 커지고, 다른 곳을 클릭하면 다시 작아집니다.

<br>

## ✓ Todo
- [x] 코스를 path로 표현
- [ ] 사용자의 위치를 실시간으로 path로 표현
- [x]  토글 기능 구현
