### ISSUE TITLE
feature : 러닝 시작전, 러닝 중 거리에 따른 타입 확인 

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#115]
## ✏️ Summary
- 사용자와 경로의 거리에 따라 러닝 타입을 확인합니다.

<br>

## ✨ Description
- 사용자의 위치와 경로의 거리를 구하여 시작전 안내문구를 띄웁니다.
- 사용자의 위치와 경로사이의 거리를 실시간으로 추적하여 자율코스 전환을 유도합니다.

<br>

## ✓ Todo
- [ ] 사용자와 경로의 거리파악
- [ ] 러닝도중 사용자가 경로를 벗어나는지 파악
- [ ] 자율코스 안내 시트
