### ISSUE TITLE
feat : iOS에서의 러닝 직전 위치 및 헬스 권한 재확인 

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#127]
## ✏️ Summary
iOS에서의 러닝 직전 위치 및 헬스 권한 재확인 

<br>

## ✨ Description
iOS에서의 러닝 직전 위치 및 헬스 권한 재확인 

<br>

## ✓ Todo
- [ ] 위치 권한 확인 
- [ ] 헬스 권한 확인 
- [ ] 확인 필요시 UI 제작 

<br>
