### ISSUE TITLE
data : 결과뷰 데이터 전달 체크

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#137]
## ✏️ Summary
- 결과뷰 데이터 표시 관련

<br>

## ✨ Description
- 결과뷰 데이터 전달 체그

<br>

## ✓ Todo
- [ ] 결과뷰 전달되는 데이터 정리
- [ ] 결과뷰 데이터 전달 체크
- [ ] 결과뷰 데이터 전달 표시
