### ISSUE TITLE
detail : 기록뷰 UI Detail

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#145]
## ✏️ Summary
기록뷰 UI Detail

<br>

## ✨ Description
기록뷰 UI Detail을 수정합니다. 

<br>

## ✓ Todo
- [x] 카테고리 칩 variable 대응 
- [ ] 기록 없을 시 ui 
- [x] 시트 커스텀 
- [ ] 상세 패딩 조절 
- [ ] stroke 굵기 및 리니어 그레디언트 추가

<br>
