### ISSUE TITLE
fix : 프로필 뷰 수정 및 InputNicknameView 수정

### ISSUE THREAD

**Issue by moonkey48** [BostonGosari/Outline#212]
## ✏️ Summary
프로필 뷰 디자인과 기능 수정 및 InputNicknameView에서 FireStore 닉네임 수정 기능 추가

<br>

## ✨ Description
프로필 뷰의 디자인 수정 내용 반영과 InputNicknameView에서 닉네임 수정 기능 추가를 진행합니다. 

<br>

## ✓ Todo
프로필 뷰 
- [ ] arrow chvron 디자인 
- [x] 전체적으로 폰트 스타일이 안먹혀있슴니다 .. 

내정보 뷰 
- [x] 내정보 수정 금지 ~!
- [ ] 생년월일,성별 리스트 높이 
- [x] 플러스 버튼 주석처리 

신체정보 
- [x] 네비게이션 타이틀, 텍스트 스타일, 리스트 스크롤 막기 
- [x] 클릭 된것만 값에 대해 primary color 적용, 수정전/수정후 완료 버튼

InputNicknameView
- [x] FireStore 닉네임 FireStore 기능 추가
