### ISSUE TITLE
fix : UI 디테일 수정 

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#213]
## ✏️ Summary
design #213 : -뷰 UI 디테일 수정 

<br>

## ✨ Description

**로그인** 
- [x] 버튼 폰트 적용 안되어있음 
- [x] 배경사진, 텍스트,로고 같이 export해서 넣기 
- [x] -- 또는 --색깔 및 텍스트 
- [x] 둘러보기 텍스트 

**토스트 바** 
- [x] 텍스트 스타일 확인 -> 문제 없음 

**기록 리스트뷰** 
- [x] 아이템 border weight, 색상. 0.3 , 날짜 색상 
- [x] 칩 상단 패딩 
- [x] 정렬 시트 상단 stroke, 시트 하단 버튼 패딩 
- [x] 시트 올라올 시 opacity 
- [x] 항목간 높이 

**기록 상세페이지** 
- [x] 헤더 날짜 텍스트 스타일 적용
- [x] Trash, NameEdit 아이콘 에셋 수정 
- [x] Date, Location 패딩 조절 (8,4)
- [x] 지도 어둡게 처리 -> path가 잘 보이도록
- [x] 지도 height 575
- [x] 단위 텍스트 색상 
- [ ] 제일 하단 패딩

**러닝 결과뷰** 
- [x] 헤더 날짜 텍스트 스타일 적용되었나요?
- [x] Title, Date 사이 padding 8
- [x] Location, Date 사이 padding 4 
- [x] Map height 524
- [x] Location, Date, 데이터 단위 텍스트 색상 
- [x] 나중에 자랑하기 언더라인 padding 4
- [x] 지도 하단 stroke 화이트 
- [x] 버튼 텍스트 굵기 
- [x] 나중에 자랑하기 텍스트 크기 다름, 하단 밑줄 
- [x] 나중에 자랑하기 -> 홈으로 돌아가기 
- [x] 상단 날짜 패딩 
- [ ] 지도 안움직이게 고정 (요거만 @hyebinsla_ 부탁드려요!! ) 

**홈탭뷰** 
- [x] 탭바 gps/자유 위치 변경 

**앗! 회원가입이 필요해요 시트** 
- [x] 계속 둘러보기 텍스트 
- [x] 에셋 크기 및 위치 조정 

**앗! 회원가입이 필요해요 뷰** 
- [x] 에셋 크기 및 위치 조정 

**자유코스** 
- [x] 헤더와 카드 사이의 공간 더 주기  
- [x] stroke linear 주기 
- [x] 자유코스 띄어쓰기 
- [x] 카드 배경 opacity 화이트로 바꾸기 
- [x] 밀어서 그리기 텍스트 크기 다름 

**러닝중 러닝 데이터 뷰** 
- [x] 케이던스 <-> 평균 페이스 바뀜 
- [x] 데이터 항목 텍스트 컬러 
- [x] 버튼 크기 및 위치 
- [x] 배경 블랙 50으로 깔기

<br>

## ✓ Todo
- [ ] 위와 같습니다. 

<br>
