### ISSUE TITLE
feature : ERD 기반 CoreData 세팅

### ISSUE THREAD

**Issue by moonkey48** [BostonGosari/Outline#23]
## ✏️ Summary
ERD 기반 CoreData 세팅

<br>

## ✨ Description
ERD에서 Record와 RunningData에 대해 CoreData를 세팅하고 Model을 구협합니다. 

<br>

## ✓ Todo
- [x] Record, RunningData, RunningType, CourseData, HealthData, Coordinate에 대해 CoreData 세팅
- [x] Record와 RunningData를 처리하는 UserDataModel 생성 및 구현
- [x] TestView 및 TestViewModel 구현

<br>
