### ISSUE TITLE
design : 결과뷰 카드 UI

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#262]
## ✏️ Summary
- 결과뷰 카드 UI 구현

<br>

## ✨ Description
- 결과뷰에 사용될 카드 UI
- 기록뷰에 사용될 미니카드 UI

<br>

## ✓ Todo
- [ ] 카드 레이아웃 구현
- [ ] 카드 인터렉션 구현
- [ ] 카드 홀로그램 구현
