### ISSUE TITLE
fix : 러닝 데이터 시트 수정

### ISSUE THREAD

**Issue by yoohyebin** [BostonGosari/Outline#279]
## ✏️ Summary
- 러닝 데이터 시트 수정

<br>

## ✨ Description
- 러닝 데이터 시트 UI 수정
- 러닝 데이터 시트 케이던스 삭제
- 러닝 뷰 인터렉션 수정

<br>

## ✓ Todo
- [ ]  러닝 데이터 시트 UI 수정
- [ ] 러닝 데이터 시트 케이던스 삭제
- [ ] 러닝 뷰 인터렉션 수정

<br>
