### ISSUE TITLE
feat : iOS에서의 러닝 세션 생성 및 운동 데이터 측정 

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#31]
## ✏️ Summary
 iOS에서의 러닝 세션 생성 및 운동 데이터 측정 

<br>

## ✨ Description
 iOS에서의 러닝 세션을 생성하고  및 운동 데이터 측정 

<br>

## ✓ Todo
- [ ]  iOS에서의 러닝 세션 생성
- [ ] request 함수 수정
- [ ] 필요한 러닝 데이터 수집 

<br>
