### ISSUE TITLE
feat : 디테일 뷰 UI 수정 및 스코어에 따른 카드 연결

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#317]
## ✏️ Summary
- 디테일뷰 UI 세부 수정
- Score 에 따른 카드 연결

<br>

## ✨ Description
- 디테일뷰 UI 를 세부 수정합니다.
- Score 에 따른 카드 연결을 구현합니다.

<br>

## ✓ Todo
- [x] 카드 Type enum 통합
- [x] Score 에 따른 카드타입 연결
- [x] 디테일뷰 UI 수정
