### ISSUE TITLE
feat : iOS 단독 러닝 시작 기능

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#36]
## ✏️ Summary
- iOS 만 가지고 있을시 러닝을 구현합니다.

<br>

## ✨ Description
- 러닝 시작, 러닝 종료 구현
- 피트니스, 건강과 데이터 연결

<br>

## ✓ Todo
- [ ] 기본 러닝 데이터 측정
- [ ] 측정한 데이터 건강, 피트니스와 연동
- [ ] 계산 러닝 데이터 측정
