### ISSUE TITLE
fix : Map 관련 오류 수정

### ISSUE THREAD

**Issue by yoohyebin** [BostonGosari/Outline#364]
## ✏️ Summary
- Map과 관련하여 발생하는 오류 및 수정사항 수정

<br>

## ✨ Description
- 가이드라인 UI 수정
- 러닝 기록뷰에 map 나타날 때 delay 있는 부분 수정
- 러닝 기록뷰 카드에 element가 너무 많아 라인이 가려지는 문제 수정
- 공유 화면 UI 수정

<br>

## ✓ Todo
- [ ] 가이드라인 color 및 width 수정
- [ ] scrollView delay 수정
- [ ] map element hidden
- [ ] 공유화면 UI 수정

<br>
