### ISSUE TITLE
fix : 홈화면 점수 별 별 표시 

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#370]
## ✏️ Summary
홈화면 점수 별 별 표시 

<br>

## ✨ Description
홈화면 점수 별 별 표시가 제대로 되지 않는 문제를 해결합ㄴ다. 

<br>

## ✓ Todo
- [ ] 코어데이터에 점수 잘 들어가는지 확인 
- [ ] 홈 뷰에서 점수 잘 끌어오는지 확인
- [ ] 점수에 따라 별을 잘 표시해주는지 확인 

<br>
