### ISSUE TITLE
design : UI 수정사항 반영

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#408]
## ✏️ Summary
- UI 수정사항을 반영합니다.

<br>

## ✓ Todo
- [x] 카드 클릭시 회전 `3번 → 2번`
- [x] 러닝 카드 그라데이션 파랑 삭제
- [x] 메인화면 카드 하단 `radius`값 `15`
- [x] 뒷 배경 그라데이션 제거 `#1F1F1F으로 고정`
- [ ] 라인 색상 그라데이션 제거 `#D5FF5D로 고정`
- [x] 텍스트 뒤에 검정 그라데이션 추가
- [x] 자유러닝 카드 불투명도 낮추기
