### ISSUE TITLE
feat : Google Analytics 적용

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#409]
## ✏️ Summary
- 요청한 GA 목록을 적용합니다.
- [링크](https://macroappleacademy.atlassian.net/wiki/spaces/B/pages/184418306/GA)

<br>

## ✨ Description
- 간단한 우선적 적용을 통해 GA를 경험해보기 위해 추가합니다.
- 추후 디테일하게 추가 예정

<br>

## ✓ Todo
- [ ] 앱 잔류시간
- [ ] 코스별 클릭수
- [ ] 러닝 시작 확인
- [ ] 자유 러닝 시작 확인
- [ ] GPS 러닝 시작 확인
- [ ] 코스 완료 확인
