### ISSUE TITLE
fix : 러닝 카드 점수 일괄 업데이트 

### ISSUE THREAD

**Issue by chamroro** [BostonGosari/Outline#421]
## ✏️ Summary
러닝 카드 점수 일괄 업데이트 

<br>

## ✨ Description
유저가 업데이트 이후 처음 앱을 처음 실행하는 딱 한번만 새로운 점수 계산 방식으로 업데이트가 이루어지고,
이후 실행 시에는 UserDefaults에 저장된 플래그로 인해 다시 업데이트되지 않을 수 있도록 수정해볼 예정입니다. 

<br>

## ✓ Todo
- [ ] UserDefaults 플래그 설정 
- [ ] 앱이 시작될 때 점수 업데이트 체크
- [ ] 테스트 (본인 기기 기록 활용) 

<br>
