### ISSUE TITLE
feature : 공유화면

### ISSUE THREAD

**Issue by yoohyebin** [BostonGosari/Outline#46]
## ✏️ Summary
- 공유 화면 UI 및 기능 개발

<br>

## ✨ Description
- 커스텀, 이미지 2개의 탭으로 구현
- 커스텀 화면
    - 커스텀 화면에서 지도에 사용자가 러닝한 경로를 표시
    - capsule을 사용해서 지도위에 표시할 정보 선택

- 이미지 화면
    -  기본 이미지, 배경 사진 선택 가능
    - 배경사진에서 카메라, 이미지 피커 선택 sheet 띄우기
        - 권한 요청 필요 및 확인
    - 사용자 이동경로를 path로 표시
        - gestue로 rotate, scale 조정, offset 조정

- 인스타 공유

<br>

## ✓ Todo
- [ ] UI 구현
- [ ] 지도에 경로 불러오기
- [ ] 카메라, 이미지 피커 연결
- [ ] 경로 Path로 그리기 + gesture
- [ ] 인스타 공유
- [ ] 사진 저장
