### ISSUE TITLE
feature : KML 데이터 추가 및 CouseData 설정

### ISSUE THREAD

**Issue by moonkey48** [BostonGosari/Outline#51]
## ✏️ Summary
코스정보 제공을 위한 KML 데이터 추가 및 CourseData 설정

<br>

## ✨ Description
코스정보 제공을 위한 KML 데이터 추가를 하고 해당 데이터를 포함해서 FireStore에 데이터를 올려둘 예정입니다. 

<br>

## ✓ Todo
- [ ] 서울: 낙타런, 캥거루런, 댕댕런, 비행기런, 오리런, 문어런 KML 파일 제작
- [ ] 포항: 댕댕런, 악어런 KML 파일 제작
- [ ] FireStore 데이터 업로드
