### ISSUE TITLE
design : 전체 UI 구현, 뷰 연결

### ISSUE THREAD

**Issue by hyunjuntyler** [BostonGosari/Outline#53]
## ✏️ Summary
- 전체 UI 를 연결하고 알림을 구현합니다.

<br>

## ✨ Description
- 전체 UI 연결
- 3, 2, 1 구현
- 알림 시트 구현

<br>

## ✓ Todo
- [x] 전체 UI 연결
- [x] 3, 2, 1 구현
- [ ] 알림 시트 구현
- [ ] 러닝 기능 연결
