### ISSUE TITLE
feature : Onboarding View 연결

### ISSUE THREAD

**Issue by moonkey48** [BostonGosari/Outline#63]
## ✏️ Summary
Onboarding View 연결

<br>

## ✨ Description
Login, Nickname, 건강정보 승인을 받는 뷰를 연결해서 메인뷰로 이동합니다. 또한 둘러보기 시 기능 제한을 위한 변수를 설정 예정입니다.

<br>

## ✓ Todo
- [x] Onboarding View 연결
- [x] Onboarding data 연결 및 저장
- [x] 둘러보기 시 온보딩 뷰 스킵 및 메인 뷰로 전환 기능 구현

<br>
